language: bash
env:
  - DOKKU_VERSION=v0.3.17
  - DOKKU_VERSION=master
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
matrix:
  allow_failures:
    - env: DOKKU_VERSION=master
script: make test
